import { getThreads } from "@/services/threads";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Thread } from "@/types/Thread";
import SideBar from "@/components/layout/side-bar";
import { getAgencyInfo } from "@/services/agency";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const agency = await getAgencyInfo();
  const threads: Array<Thread> = await getThreads();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar agencyName={agency.name} threads={threads}>
          {children}
        </SideBar>
      </body>
    </html>
  );
}
